'use client';

/**
 * رجیستری آیکون‌ها
 * به‌جای import کل پکیج lucide-react (که حجم باندل را زیاد می‌کند)،
 * فقط آیکون‌های استفاده‌شده با نام نگاشت می‌شوند و با prop `name` صدا زده می‌شوند.
 */
import {
  Activity,
  AlarmClock,
  ArrowLeft,
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  Award,
  Baby,
  Bike,
  Brush,
  Banknote,
  BarChart3,
  Bell,
  BookHeart,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Clock,
  CloudSun,
  Coffee,
  Columns3,
  Copy,
  CornerDownLeft,
  Cpu,
  Download,
  Droplets,
  Dumbbell,
  Eye,
  EyeOff,
  Feather,
  Filter,
  Flame,
  Flower2,
  Folder,
  FolderKanban,
  FolderOpen,
  Footprints,
  Gamepad2,
  Gift,
  Goal,
  GraduationCap,
  Grid2x2,
  Heart,
  HeartPulse,
  Home,
  Image as ImageIcon,
  Info,
  KeyRound,
  Languages,
  Laptop,
  Leaf,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link as LinkIcon,
  ListChecks,
  ListFilter,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Milestone,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Palette,
  Paperclip,
  Pause,
  PenLine,
  Pencil,
  Pill,
  Pin,
  PinOff,
  Play,
  Plus,
  QrCode,
  Quote,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Route,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SkipForward,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  StickyNote,
  Sun,
  Sunrise,
  Tag,
  Target,
  Thermometer,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  Wallet,
  Wand2,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  Activity, AlarmClock, ArrowLeft, AlertCircle, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, Award, Baby, Bike, Banknote,
  BarChart3, Bell, BookHeart, BookOpen, Bookmark, Brain, Briefcase, Brush, Bus, Calendar, CalendarCheck,
  CalendarDays, Check, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle,
  CircleDot, Clock, CloudSun, Coffee, Columns3, Copy, CornerDownLeft, Cpu, Download, Droplets, Dumbbell, Eye,
  EyeOff, Feather, Filter, Flame, Flower2, Folder, FolderKanban, FolderOpen, Footprints, Gamepad2, Gift, Goal,
  GraduationCap, Grid2x2, Heart, HeartPulse, Home, ImageIcon, Info, KeyRound, Languages, Laptop, Leaf,
  LayoutDashboard, LayoutGrid, Lightbulb, LinkIcon, ListChecks, ListFilter, Loader2, Lock, LogOut, Mail, MapPin,
  Maximize2, Menu, Milestone, Minimize2, Minus, Monitor, Moon, MoreHorizontal, MoreVertical, Music, Palette,
  Paperclip, Pause, PenLine, Pencil, Pill, Pin, PinOff, Play, Plus, QrCode, Quote, Receipt, RefreshCw, Repeat, Rocket,
  RotateCcw, Route, Save, Scale, Search, Send, Settings, Share2, Shield, ShoppingBag, ShoppingCart, SkipForward,
  Smartphone, Sparkles, Sprout, Star, StickyNote, Sun, Sunrise, Tag, Target, Thermometer, Timer,
  Trash2, TrendingDown, TrendingUp, Trophy, Upload, User, Users, Utensils, UtensilsCrossed, Volume2, VolumeX,
  Wallet, Wand2, Wind, X, Zap,
};

/** نام‌های جایگزین برای آیکون‌هایی که در نسخه فعلی lucide موجود نیستند */
ICONS.Stopwatch = AlarmClock;
ICONS.Target2 = Goal;
ICONS.Utensils2 = Utensils;

export interface IconProps extends Omit<React.ComponentProps<'svg'>, 'name'> {
  name: string;
  size?: number;
  strokeWidth?: number;
}

/** آیکون پویا با نام — در صورت نبود نام، آیکون پیش‌فرض نمایش داده می‌شود */
export function Icon({ name, size = 18, strokeWidth = 1.9, className, ...rest }: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} {...rest} />;
}

export default Icon;
